name: Bhoomi Data Scraper

on:
  schedule:
    # Runs at 02:00 UTC every day (7:30 AM IST)
    - cron: '0 2 * * *'
  workflow_dispatch: # Allows you to run it manually from the Actions tab

jobs:
  scrape-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # Removed playwright-stealth, as we are switching strategy
          pip install playwright requests
          # Ensure all browsers are installed
          python -m playwright install --with-deps

      - name: Run the scraper script
        id: scraper
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python scraper.py

      # This step runs ONLY if the scraper fails
      - name: Upload screenshot on failure
        if: failure() && steps.scraper.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: error-screenshot
          path: error_screenshot.png
